export { default as AstroInfo } from './AstroInfo';
export { default as  EducationalInfo} from './EducationalInfo';
export { default as  FamilyInfo} from './FamilyInfo';
export { default as  PersonalInfo} from './PersonalInfo';
export { default as  Preference} from './Preference';
export { default as  ProfessionalInfo} from './ProfessionalInfo';
export { default as  ReligionInfo} from './ReligionInfo';
export { default as  Hobbies} from './Hobbies';
export { default as You } from './You';
export { default as Date } from './Date';
